proyecto_vehiculos_django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

from . import views

handler403 = views.custom_403_view

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('vehiculo/', include('vehiculo.urls')),
    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
]

usuarios/urls.py
from django.urls import path
from .import views

app_name = 'usuarios'

urlpatterns = [
    path('registro/', views.registro, name='registro'),
    path('cerrar_sesion/', views.logout_view, name='cerrar_session'),
    path('inicio_sesion/', views.login_view, name = 'login'),
]

vehiculo/urls.py
from . import views
from django.urls import path

app_name = 'vehiculo'
urlpatterns = [
    # path('', views.index, name='vehiculo_index'),
    path('add/', views.agregar_vehiculo, name='agregar_vehiculo'),
    path('listar/', views.listar, name='listar'),
]

usuarios/models.py
from django.db import models

# Create your models here.

vehiculo/models.py
from django.db import models

# Create your models here.
class Vehiculos(models.Model):
    marca = models.CharField(max_length=20, default='Ford')
    modelo = models.CharField(max_length=100)
    serial_carroceria = models.CharField(max_length=50)
    serial_motor = models.CharField(max_length=50)
    categoria = models.CharField(max_length=20, default='Particular')
    precio = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    # Crear restricion para precio

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistroForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

vehiculo/forms.py
from django import forms
from .models import Vehiculos

class VehiculosForm(forms.ModelForm):
  # fecha_creacion = forms.DateTimeField(widget=forms.DateTimeInput(
  #     attrs={'type': 'datetime-local'}), input_formats=['%d-%m-%YT%H:%M'])
  # fecha_modificacion = forms.DateTimeField(widget=forms.DateTimeInput(
  #     attrs={'type': 'datetime-local'}), input_formats=['%d-%m-%YT%H:%M'])

  class Meta:
    model = Vehiculos
    # campos que tiene el modelo
    fields = ['marca', 'modelo', 'serial_carroceria',
              'serial_motor', 'categoria', 'precio']

proyecto_vehiculos_django/views.py
from django.shortcuts import render
from django.template import RequestContext

def index(request):
    return render(request, 'index.html')


def custom_403_view(request, exception): 
    context = { 
                "message": "No tienes permiso para acceder a esta página." 
            } 
    return render(request, "403.html", context)

usuarios/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group
from .forms import RegistroForm
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib.auth import login as auth_login

# Create your views here.

def registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            grupo_usuario = Group.objects.get(name = 'Usuario')
            user.groups.add(grupo_usuario)
            return redirect('login')
    else:
        form = RegistroForm()
        return render(request,'usuarios/registro.html',{'form': form})
        
def logout_view(request):
    logout(request)
    messages.success(request,'Has cerrado la sesion')
    return redirect('usuarios:login')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            messages.success(request, 'Se ha iniciado sesion con éxito')
        # user1 = request.user
        if request.user.is_superuser:
            grupo =  "Administrador"
        else:
            grupo = request.user.groups.values_list('name', flat=True).first()
        print(grupo)
        request.session['grupo'] = grupo

        return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'usuarios/login.html',{'form': form })

vehiculo/views.py
from .forms import VehiculosForm
from django.shortcuts import render, redirect
from .models import Vehiculos
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied



# Create your views here.
@login_required()
@permission_required('vehiculo.add_vehiculos', raise_exception=True)
def agregar_vehiculo(request): 
    if request.method == 'POST': 
        form = VehiculosForm(request.POST) 
        if form.is_valid(): 
            form.save() 
            messages.success(request, 'El vehículo ha sido agregado con éxito') 
            return redirect('vehiculo:agregar_vehiculo') 
    else: 
        form = VehiculosForm() 
    return render(request, 'vehiculo/agregar.html', {'form': form})

@login_required()
@permission_required('vehiculo.view_vehiculos', raise_exception=True)
def listar(request):
    vehiculos = []
    try: 
        # bajo,  entre  0  y  10000
        # vehiculos = Vehiculos.objects.filter(precio_alto = precio)
        vehiculos = Vehiculos.objects.all()
        # vehiculos = Vehiculos
        if not vehiculos:
            raise ValueError("No hay vehiculos en este momento.")
    except Exception as e:
        return render(request, 'vehiculo/listar.html'),{'error': 'Se produjo un error inesperado.'}
    context={
        # 'todos_los_vehiculos':vehicul,
        'vehiculos': vehiculos
    }
    
    return render(request, 'vehiculo/listar.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="" />
    <meta name="robots" content="index,follow" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% comment %}
    <link rel="stylesheet" href="{% static 'css/styles.css'  %}"> {% endcomment %}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">Vehiculos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expend="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto d-flex w-100">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'index' %}">Inicio</a>
                        </li>

                        {% if user.is_authenticated %}
                            {% if request.session.grupo == 'Administrador' %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'vehiculo:agregar_vehiculo' %}">Agregar</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'vehiculo:listar' %}">Listar</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'vehiculo:listar' %}">Listar</a>
                                </li>
                                <li class="nav-item ms-auto"></li>
                            {% endif %}
                            <li class="nav-item ms-auto"></li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'usuarios:cerrar_session' %}">Salir</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link">Hola {{ user }}</a>
                            </li>
                        {% else %}
                        <li class="nav-item ms-auto"></li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'usuarios:login' %}">Iniciar sesión</a>
                                </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container mt-4">
        {% if messages %}
        <div>
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% block content %}{% endblock %}
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    {% comment %}
    <script src="{% static 'js/scripts.js' %}"></script> {% endcomment %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Pagina Principal{% endblock %}

{% block content %}
<h1 class="text-center">Catalogo de Vehiculos</h1>
<div class="container-fluid text-center">
    <img src="{% static 'img/102.jpg' %}" alt="imagen catalogo vehiculos" >
</div>
{% endblock %}

usuarios/templates/usuarios/login.html
{% extends 'base.html' %}
{% block title %} Registro {% endblock %}

{% block content %}
<h1>Iniciar Sesion</h1>
<!-- envio de formulario -->
<form class="form" method="POST">
  <!-- seguridad para evitar ataques cruzados con token -->
  {% csrf_token %}
  <!-- metodo renderizar formulario dentro de un parrafo -->
  {{form.as_p}}
  <button type="submit" class="btn- btn-primary">Ingresar</button>
</form>
{% endblock %}

usuarios/templates/usuarios/registro.html
{% extends 'base.html'%} 
{% block title %} Registro {% endblock %}

{% block content %}
<h2> Registro de usuario </h2>
<form method="post">
    {% csrf_token %} {{form.as_p}}
    <button type="submit" class="btn btn-primary">Registrarse</button>
</form>

{% endblock %}

vehiculo/templates/vehiculo/agregar.html
{% extends 'base.html' %}


{% block title %} {% endblock %}
Agregar Vehiculo
{% block content %}

<div class="text-align: center;">

  <h1>Agregar Vehiculo</h1>
</div>
<div>
  <form method="post">

    {% csrf_token %}

    {{form.as_p}}
    <button type="submit">Enviar</button>
  </form>
</div>

{% endblock %}

vehiculo/templates/vehiculo/listar.html
{% extends 'base.html' %}

{% block title %}Lista Vehiculos{% endblock %}

{% block content %}


<h1>Listar</h1>

<!-- {% if error %}
<div class="alert alert-danger">{{error}}</div>
{% endif %} -->

{% if vehiculos %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Marca</th>
        <th scope="col">Modelo</th>
        <th scope="col">Serial Carroceria</th>
        <th scope="col">Serial Motor</th>
        <th scope="col">Categoria</th>
        <th scope="col">Precio</th>
        <th scope="col">Condicion de Precio</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        {% for vehiculo in vehiculos %}
        <td>{{vehiculo.marca}}</td>
        <td>{{vehiculo.modelo}}</td>
        <td>{{vehiculo.serial_carroceria}}</td>
        <td>{{vehiculo.serial_motor}}</td>
        <td>{{vehiculo.categoria}}</td>
        <td>{{vehiculo.precio}}</td>
        <!-- bajo, entre 0 y 10000; Medio, para mayores de 10000 y 30000; -->
        {% if vehiculo.precio <= 10000 %}
        <!-- <td>{{vehiculo.precio}}</td> -->
          <td>Bajo</td>
        {% elif vehiculo.precio > 10000 and vehiculo.precio < 30000  %}
          <td>Medio</td>
        {% else %}
          <td>Alto</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
<p>No hay vehiculos disponibles actualmente</p>
{% endif %}

{% endblock %}